export * from './create-translation.dto';
export * from './create-word.dto';
export * from './language-action.dto';
export * from './login-credentials.dto';
export * from './project-action.dto';
export * from './update-several-translations.dto';
export * from './update-translation.dto';
export * from './update-translation-by-id.dto';
export * from './add-language-configuration.dto';
